# Jekyll Resume Theme

# Site settings
title: Allison Gaines
email: alpinosky@gmail.com
description: Allison Gaines online resume.
baseurl: ""
url: "apinosky.github.io"
name: Allison (Pinosky) Gaines
job: Robotics and Machine Learning Engineer
location: Chicago, IL
interests: Robotics
  # twitter_username: apinosky
github_username:  apinosky
  # codepen_username:
linkedin_username: allisonpinosky
scholar_username: gw1wHMEAAAAJ 
email_address: alpinosky@gmail.com
update_year: 2025
google_site_verification: 6y59grYeqAE5l8gCSdbVvTtnS4XhtTNG4kXcmmN_oaU

# Build settings
markdown: kramdown
theme: minima
plugins: 
  - jekyll-seo-tag