# Jekyll Resume Theme

# Site settings
title: Allison Gaines
email: alpinosky@gmail.com
description: Allison Gaines online resume.
baseurl: ""
url: "apinosky.github.io"
name: Allison (Pinosky) Gaines
job: Robotics and Machine Learning Engineer
location: Chicago, IL
interests: Robotics
  # twitter_username: apinosky
github_username:  apinosky
  # codepen_username:
linkedin_username: allisonpinosky
email_address: alpinosky@gmail.com
update_year: 2024
num_jobs: 3
num_pubs: 6

# Build settings
markdown: kramdown
